### PR TITLE
Badger wallet incorrectly displays some characters.

### PR DESCRIPTION
**Pull request by A-Chewy-1**
I created a token called Consent, ticker: ( ͡° ͜ʖ ͡°) which Badger displays as ( M!B0 MJ M!B0)

Often times people are unaware that I've given them my Consent! Please fix!

https://simpleledger.info/#token/8aab2185354926d72c6a8f6bf7e403daaf1469c02e00a5ad5981b84ea776d980

### CODE REVIEW

**Comment by sindresorhus** [comment]
From the readme:

> (We don't accept pull request contributions for new or updated icons at this time. Open an issue and we'll do the icon for you.)

---

You also need to be listed on CMC, so that we now it's an established coin.

**Comment by lukechilds** [comment]
Also, as far as I can tell this didn't add an icon, it just deleted a load of files 🤔

**Comment by lukechilds** [comment]
@A-Chewy-1 I think you're getting confused, this repo is nothing to do with Badger Wallet.

This is a repo for cryptocurrency icons. We don't have your token included in our project in any way.

**Comment by A-Chewy-1** [comment]
I recognize that I am at fault, however Im_uname has betrayed me. Thank you Luke.

**Pull request closed without merging**
