### PR TITLE
Add and update icons

### LINKED ISSUE #112: Add HOdlcoin (HODL)
Logo: http://hodlcoin.com/img/logo.svg
Info: http://hodlcoin.com

### LINKED ISSUE #114: Add SafeCoin (SAFE)
Great project!  Please include SafeCoin :)
[SAFE]

https://bitcointalk.org/index.php?topic=2838370.0

http://safecoin.org
[logos updated.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2037705/logos.updated.zip)

### LINKED ISSUE #122: Add Storiqa (STQ)
Please add token Storiqa (STQ),
cmc: [https://coinmarketcap.com/currencies/storiqa/](https://coinmarketcap.com/currencies/storiqa/)
image: [https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p320x320/20246018_1976532582614836_2357846549826288209_n.png?_nc_cat=0&_nc_eui2=AeEoYWqLU7WobHRvPQ3jOQmQSv6GjpUAwXJ7QQdsJ3fcEimQ4S5dFOx5dgLkT6HGr-UIRu1SS1zwSYtk0ryLr3HFE0vvW0hmXLsTcWY2MvhjMg&oh=fdaedbe24daf1ff4112f9005866ba4c2&oe=5B7D2FC3](https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p320x320/20246018_1976532582614836_2357846549826288209_n.png?_nc_cat=0&_nc_eui2=AeEoYWqLU7WobHRvPQ3jOQmQSv6GjpUAwXJ7QQdsJ3fcEimQ4S5dFOx5dgLkT6HGr-UIRu1SS1zwSYtk0ryLr3HFE0vvW0hmXLsTcWY2MvhjMg&oh=fdaedbe24daf1ff4112f9005866ba4c2&oe=5B7D2FC3)

### LINKED ISSUE #127: Add Neumark (NEU)
Please add Neumark (NEU) logo:
Vector:
https://neufund.org/cms_resources/neumarkcolor-1.eps
https://neufund.org/cms_resources/admin/neumarkcolor-1.svg
PNG:
https://neufund.org/cms_resources/neumarkcolor.png

### LINKED ISSUE #129: Update OST (OST)
Hi team,

Could you please update the OST icon on Delta app to reflect our rebranding ([ost.com](https://ost.com))?

I've attached an SVG file inside a zip.

Thank you!
Ignas

[Logo-Icon_SVG.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2072355/Logo-Icon_SVG.zip)

### LINKED ISSUE #131: Add VerusCoin (VRSC)
Info: https://veruscoin.io/
Icon: https://github.com/VerusCoin/Media-Assets/blob/master/Logos/SVG/VRSC.svg

### LINKED ISSUE #135: Add ColossusXT (COLX)
Hi,
Can you add ColossusXT (COLX) please?
This folder contains all our media logos/icons/etc.
https://github.com/ColossusCoinXT/Media/blob/master/COLX%20Media%20-%20Logos.zip

Kind regards,
Ciwox
ColossusXT

### LINKED ISSUE #137: Update XRP (XRP)
Ripple seems to have introduced a new icon for XRP.
See https://coinmarketcap.com/currencies/ripple/

### LINKED ISSUE #143: Add BitCloud (BTDX)
Hi Team,

please add our BitCloud icons / images. 
[Cryptocurrency-Icons.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2135414/Cryptocurrency-Icons.zip)

If you need more Infos, please let me know.

Thank you,
Lukas

### LINKED ISSUE #148: Add GLX Token (GXLT)
Source: [GLXT.svg.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2164979/GLXT.svg.zip)
Info: https://glx.co/glxt/
Brand guidelines: https://glx.co/media-kit/

### LINKED ISSUE #151: Update Dash (DASH)
The Dash project recently updated their logo:

https://www.dash.org/graphics/

Thanks.

### LINKED ISSUE #154: Add Dropil (DROP)
Link to logos: https://dropil.com/branding/

### LINKED ISSUE #161: Add TrueUSD (TUSD)
https://www.trusttoken.com/trueusd/
https://coinmarketcap.com/currencies/trueusd/

Media kit here, but no vector: https://drive.google.com/drive/folders/1W26zVFU5pEgWAuaVzm-abELnaxVYjUbl

**We need help finding a vector version of their logo.**

### LINKED ISSUE #172: Add Pundi X (NPXS)
https://pundix.com/
https://coinmarketcap.com/currencies/pundi-x/

**We need help finding a vector version of their logo.**

### LINKED ISSUE #173: Add Huobi Token (HT)
https://www.huobi.com/en-us/
https://coinmarketcap.com/currencies/huobi-token/

**We need help finding a vector version of their logo.**

### LINKED ISSUE #177: Add Aeon (AEON)
Official website: https://www.aeon.cash/
CoinMarketCap: https://coinmarketcap.com/currencies/aeon/
CoinLib: https://coinlib.io/coin/AEON/AeonCoin

Their branding pack is available here: https://www.dropbox.com/sh/l6db52ehs6trzfb/AADFyL0s2I2a4JkXX0wH4Zs2a?dl=0 (this link comes from their Reddit: https://www.reddit.com/r/aeon)

They started discussing just a few days ago to make them available in their official homepage repo https://github.com/aeonix/aeonix.github.io (the source code of https://www.aeon.cash/) in their [issue #34](https://github.com/aeonix/aeonix.github.io/issues/34) and [pull request #36](https://github.com/aeonix/aeonix.github.io/pull/36). 👍

### LINKED ISSUE #178: Add Monero Original (XMO)
Official website: https://monero-original.org/
CoinMarketCap: https://coinmarketcap.com/currencies/monero-original/
CoinLib: https://coinlib.io/coin/XMO/Monero+Original

Useful resources:

- https://github.com/XmanXU/monero-gui/tree/master/images/appicons
- https://github.com/XmanXU/monero-original/blob/master/logo.svg

### LINKED ISSUE #179: Add Masari (MSR)
Official website: https://getmasari.org/
CoinMarketCap: https://coinmarketcap.com/currencies/masari/
CoinLib: https://coinlib.io/coin/MSR/

Useful resources:

- https://github.com/masari-project/Masari-Branding-Guide/blob/master/Logo/SVG/Masari_Icon.svg
- https://github.com/masari-project/Masari-Branding-Guide/blob/master/Logo/PNG/Masari_Icon.png

### PR DESCRIPTION
**Pull request by NadiaSotnikova**
Created and updated icons for:

- aeon (Fixes #177)
- btdx (Fixes #143)
- colx (Fixes #135)
- dash (Fixes #151)
- drop (Fixes #154)
- gxlt (Fixes #148)
- hodl (Fixes #112)
- ht (Fixes #173)
- msr (Fixes #179)
- neu (Fixes #127)
- npxs (Fixes #172)
- ost (Fixes #129)
- safe (Fixes #114)
- stq (Fixes #122)
- tusd (Fixes #161)
- vrsc (Fixes #131)
- xmo (Fixes #178)
- xrp (Fixes #137)

All images are imageOptim optimized.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The icons look really good 🙌

**Comment by sindresorhus** [comment]
I've noticed you accidentally included `svg/.DS_Store`. This is just an annoying system metafile produced by macOS and should not be included in the repo. Unfortunately, Git doesn't exclude it by default (It really should...). You can run these commands in the Terminal app to fix it and prevent it from being added in the future:

```
find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch
```
```
git config --global core.excludesfile ~/.gitignore
```
```
echo .DS_Store >> ~/.gitignore
```

**Comment by sindresorhus** [comment]
I noticed the `svg/icon` files are not minified. Is that intentional? They can safely be minified by ImageOptim if you turn off the `svgcleaner` optimization in Preferences.

**Comment by sindresorhus** [comment]
For each icon, can you reference the issue it fixes? This is useful to have a link to the issue when looking through the issue tracker and it will also automatically close the issue when this pull request is merged.

It should be in this format:

```
Fixes #177
Fixes #143
```

Where #177, for example, is the issue number for `aeon`.

**Comment by lukechilds** [comment]
@NadiaSotnikova Just for future reference it's important that the text is exactly `Fixes #123` not just `#123` as this will link the issues to the PR and mark them as closed automatically when we merge this PR.

No worries, I've updated it for now.

SVG icons look great but all the new PNG versions seem to be corrupt.

e.g: https://github.com/atomiclabs/cryptocurrency-icons/blob/b252e7514953662c14c9da0354133181b7179081/128/black/gxlt.png

**Comment by c1xx** [comment]
Thank you very much for adding Bitcloud (BTDX) icons 👍

**Comment by NadiaSotnikova** [comment]
Hey @lukechilds ! Thanks for fixing the text! 

I updated the PNGs but they're still corrupted. Tried doing it without ImageOptim, still same result. The files are fine upon export, but something goes wrong when I make a commit/ push the changes. Maybe you have an idea what the issue might be?

**Comment by syeo66** [comment]
@NadiaSotnikova It looks like you're using Windows and your machine is treating the files as text files on upload (adding \r\n while it should not do that). According to [Stackoverflow](https://stackoverflow.com/questions/28582394/committed-png-files-to-git-on-windows-broke-png-r-n-header) adding `*.png binary` to .gitattributes and recommit the files might help.

**Comment by syeo66** [comment]
Thank you very much, @NadiaSotnikova 👍

**Comment by sindresorhus** [comment]
@NadiaSotnikova The `/svg/icon/btc.svg` icon looks faded out like seen in https://github.com/atomiclabs/cryptocurrency-icons/issues/145 Are you sure you disabled the `svgcleaner` optimization in ImageOptim and that you're using the latest version of ImageOptim? I just tried optimizing `/svg/icon/btc.svg` with ImageOptim and it doesn't become faded out. I think the best would for you to revert the SVG optimization change. That should really be a separate change anyway as it's not related to updating the icons.

**Comment by NadiaSotnikova** [comment]
Hi @sindresorhus ! Yes, totally haven't disabled the svgcleaner optimization in ImageOptim. I reverted the SVG optimization change.

**Comment by sindresorhus** [comment]
@NadiaSotnikova I don't think you fully reverted the SVG optimization change as there are still many changed SVGs that are not related to the newly added icons. For example: https://github.com/atomiclabs/cryptocurrency-icons/blob/2e06c92e50d740a0784ce7385a8c3d63c6d8154a/svg/icon/bcd.svg (which looks faded)

When looking at the diff here, https://github.com/atomiclabs/cryptocurrency-icons/pull/181/files, only the newly added or improved icons (from the list in your PR body text) should be in the diff.

**Comment by sindresorhus** [comment]
I've fixed the issue.

**Comment by sindresorhus** [comment]
Great work on the icons, @NadiaSotnikova 🙌✨

**Comment by paulofreitas** [comment]
Thank you very much for all the new icons, @NadiaSotnikova! Great work, much appreciated!! 👏 ✨

**Comment by lukechilds** [comment]
@NadiaSotnikova You rock 🤘

**Pull request merged**
