### PR TITLE
Update DNR to D

### PR DESCRIPTION
**Pull request by carsenk**
This is a PR to update DNR namings to D and to also get it inline with the new readd/PR on HyperDEX.

### CODE REVIEW

**Comment by carsenk** [comment]
@sindresorhus @atomiclabs Can this please be merged? Thanks!

**Comment by sindresorhus** [comment]
You did not update the names for the SVG icons.

**Comment by carsenk** [comment]
I do not believe we had an svg?

**Comment by carsenk** [comment]
We do have a Visual Guide with all sorts of our icons available in AI format mostly at https://denarius.wiki but I do believe we only had PNGs previously in this repo

**Comment by lukechilds** [comment]
@carsenk all icons should be listed in all formats/styles unless there is an error.

You can view your SVG icons here: https://github.com/atomiclabs/cryptocurrency-icons/commit/df67b9e48ead8c6241fddbbd6725a698ae756127

**Comment by carsenk** [comment]
Ah gotcha, Yea we had em, my bad. Sweet!

**Pull request merged**
