### PR TITLE
Missing manifest.json on npm

### PR DESCRIPTION
**Pull request by quentinus95**
We are missing the manifest.json file when installing the dependency using NPM. Can you release this fix in a `0.9.1`? Thx!

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's intentionally not included in the npm. The manifest is meant only for the website.

**Comment by quentinus95** [comment]
Actually, the manifest was initially introduced to allow frontend applications to automatically discover the list of supported icons (see the file history). It would be nice to have it back!

**Comment by quentinus95** [comment]
@sindresorhus Why can't this be merged? It was extremely useful and I don't see any issue it may cause...

**Comment by quentinus95** [comment]
Awesome thanks!

**Pull request closed without merging**
