### PR TITLE
added viewBox and standardized attribute order

### PR DESCRIPTION
**Pull request by ackushiw**
I made sure all svg icons in /black, /color and /white use `viewBox`

I've also standardized the attribute order to alphabetical, if there is a more widely used standard for SVGs let me know and I can change it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> I've also standardized the attribute order to alphabetical

The attribute order doesn't matter. Just leave it as it were.

**Comment by ackushiw** [comment]
Even though the attribute order doesn't technically matter, standardization will help with future updates.

**Comment by sindresorhus** [comment]
I’m willing to accept the order thing if you can automate it with SVO or some other tool.

**Comment by sindresorhus** [comment]
But it should be a separate PR. This PR should be focused on adding viewBox. It’s currently impossible to review that because of the unrelated ordering change.

**Comment by sindresorhus** [comment]
You can use https://github.com/guylando/svgo-addViewBox/blob/master/addViewBox.js See: https://github.com/svg/svgo/issues/722#issuecomment-385028841

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
